# Generated by Django 5.2.5 on 2025-08-25 14:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('anio_universitario', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('sigla', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.PositiveIntegerField()),
                ('tipo_materia', models.CharField(max_length=50)),
                ('ciclo_lectivo', models.PositiveIntegerField()),
                ('turno_cursado', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('horario', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id_tipo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id_alumno_curso', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='UTN.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='UTN.curso')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCurso',
            fields=[
                ('id_materia_curso', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='UTN.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='UTN.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_codigo_alfanumerico', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='inscripto', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.alumno')),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.materiacurso')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='UTN.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='UTN.materia')),
            ],
        ),
        migrations.CreateModel(
            name='CondicionFinal',
            fields=[
                ('id_condicion_final', models.AutoField(primary_key=True, serialize=False)),
                ('condicion', models.CharField(choices=[('regular', 'Regular'), ('libre', 'Libre'), ('aprobacion_directa', 'Aprobación Directa'), ('promocion_practica', 'Promoción Práctica')], max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='UTN.reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('condicion_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='UTN.condicionfinal')),
                ('tipo_evaluacion', models.ForeignKey(choices=[('parcial_teorico', 'Parcial Teórico'), ('parcial_practico', 'Parcial Práctico'), ('trabajo_practico', 'Trabajo Práctico')], on_delete=django.db.models.deletion.CASCADE, to='UTN.tipoevaluacion')),
            ],
        ),
    ]
