# Generated by Django 5.2.5 on 2025-12-11 12:04

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_anios', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id_tipo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('dni', models.CharField(default='', max_length=20, unique=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('anio_universitario', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='UTN.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre', models.CharField(default='', max_length=100)),
                ('sigla', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ciclo_lectivo', models.PositiveIntegerField()),
                ('correlativas_requeridas', models.ManyToManyField(blank=True, related_name='materias_que_la_requieren', to='UTN.materia', verbose_name='Materias Correlativas Requeridas')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaCurso',
            fields=[
                ('id_materia_curso', models.AutoField(primary_key=True, serialize=False)),
                ('turno_cursado', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('horario', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='UTN.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_ofrecidos', to='UTN.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_codigo_alfanumerico', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('inscripto', 'Inscripto'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='inscripto', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.alumno')),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.materiacurso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionFinal',
            fields=[
                ('id_condicion_final', models.AutoField(primary_key=True, serialize=False)),
                ('condicion', models.CharField(choices=[('regular', 'Regular'), ('libre', 'Libre'), ('aprobacion_directa', 'Aprobación Directa'), ('promocion_practica', 'Promoción Práctica')], max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='UTN.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='UTN.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('condicion_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='UTN.condicionfinal')),
                ('tipo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.tipoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='CarreraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.materia')),
            ],
            options={
                'unique_together': {('carrera', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_estado', to='UTN.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_alumnos', to='UTN.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='AlumnoMateriaCurso',
            fields=[
                ('id_alumno_materia_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_curso', to='UTN.alumno')),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='UTN.materiacurso')),
            ],
            options={
                'unique_together': {('alumno', 'materia_curso')},
            },
        ),
        migrations.CreateModel(
            name='ProfesorMateriaCurso',
            fields=[
                ('id_profesor_mc', models.AutoField(primary_key=True, serialize=False)),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='UTN.materiacurso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'materia_curso')},
            },
        ),
    ]
