# Generated by Django 5.2.5 on 2025-09-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='tipo_materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='sigla',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CarreraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.materia')),
            ],
            options={
                'unique_together': {('carrera', 'materia')},
            },
        ),
    ]
