# Generated by Django 5.2.5 on 2025-09-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0002_remove_materia_carrera_remove_materia_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='materia_curso',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='materia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.materiacurso'),
        ),
        migrations.DeleteModel(
            name='AlumnoCurso',
        ),
    ]
