# Generated by Django 5.2.5 on 2025-10-11 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0003_remove_inscripcion_materia_curso_inscripcion_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='anio_universitario',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
