# Generated by Django 5.2.5 on 2025-10-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0004_alter_alumno_anio_universitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contrasenia',
            field=models.CharField(default='', max_length=100),
        ),
    ]
