# Generated by Django 5.2.5 on 2025-10-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0005_alumno_contrasenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='materia',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='materia_curso',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='UTN.materiacurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiacurso',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.tipoevaluacion'),
        ),
    ]
