# Generated by Django 5.2.5 on 2025-10-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0005_alumno_contrasenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiacurso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_ofrecidos', to='UTN.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnomateriacurso',
            unique_together={('alumno', 'materia_curso')},
        ),
    ]
