# Generated by Django 5.2.5 on 2025-10-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0007_alumno_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='contrasenia',
        ),
    ]
