# Generated by Django 5.2.5 on 2025-10-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0006_alumnomateriacurso_fecha_inscripcion_and_more'),
        ('UTN', '0008_remove_alumno_contrasenia'),
    ]

    operations = [
    ]
