# Generated by Django 5.2.5 on 2025-10-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0009_merge_20251027_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnomateriacurso',
            name='fecha_inscripcion',
        ),
    ]
