# Generated by Django 5.2.5 on 2025-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0010_remove_alumnomateriacurso_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nota del 1 al 10', null=True),
        ),
    ]
