# Generated by Django 5.2.5 on 2025-12-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0012_profesor_user_alter_profesorcurso_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnomateriacurso',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfesorMateriaCurso',
            fields=[
                ('id_profesor_mc', models.AutoField(primary_key=True, serialize=False)),
                ('materia_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores_asignados', to='UTN.materiacurso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='UTN.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'materia_curso')},
            },
        ),
        migrations.DeleteModel(
            name='ProfesorCurso',
        ),
    ]
