# Generated by Django 5.2.5 on 2025-12-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0013_alter_alumnomateriacurso_nota_profesormateriacurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='correlativas_requeridas',
            field=models.ManyToManyField(blank=True, related_name='materias_que_la_requieren', to='UTN.materia', verbose_name='Materias Correlativas Requeridas'),
        ),
        migrations.AlterField(
            model_name='profesormateriacurso',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='UTN.materiacurso'),
        ),
        migrations.AlterField(
            model_name='profesormateriacurso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN.profesor'),
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_estado', to='UTN.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_alumnos', to='UTN.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia')},
            },
        ),
    ]
