# Generated by Django 5.2.5 on 2025-12-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0014_materia_correlativas_requeridas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesormateriacurso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='UTN.profesor'),
        ),
    ]
