# Generated by Django 5.2.5 on 2025-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0015_alter_profesormateriacurso_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='imagen_url_c',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='imagen_url_m',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
