# Generated by Django 5.2.5 on 2025-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0015_alter_profesormateriacurso_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='nota_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='nota_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='nota_3',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnomateriacurso',
            name='promedio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
