# Generated by Django 5.2.5 on 2025-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0016_alumnomateriacurso_finalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreramateria',
            name='anio',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
