# Generated by Django 5.2.5 on 2025-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTN', '0016_carrera_imagen_url_c_materia_imagen_url_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='imagen_url_c',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='imagen_url_m',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
