erDiagram
carrera{
    str carrera pk
    str descr
}
Alumno{
    str DNI pk
    int Fecha_nacimiento
    str Nombre
    str carrera fk
    str CondicionAlumno fk
}
Materia{
    str sigla pk
    str nombre
}
Curso{
    str Codigo pk
    str Horario
    int modulo
    int nivel
}
Condición_alumno{
    str CondicionAlumno pk
}

Inscripción{
    str CodigoINSCR pk
    int Ciclo_Lectivo
}
Evaluación{
    str tipoDeEvalucaion pk
    int Nota
    str sigla fk
    str docente
    int fecha
    int horario
}
Condición_Final{
    str Condición_Final pk
}


Alumno ||--o{ Inscripción : realiza
Inscripción ||--o{ Materia : Inscribe
Inscripción ||--o{ Condición_alumno : determina
carrera ||--o{ Alumno: Tiene
Materia ||--o{ Curso: Tiene
Condición_alumno }o--|| Alumno: Tiene
Curso ||--o{ Evaluación: tiene
Alumno ||--o{ Evaluación: rinde
Evaluación }o--|| Condición_Final: determina
Alumno||--o{ Condición_Final: tiene